/*Inserciones de datos*/
/*Inserciones tabla estado_equipo*/
INSERT INTO estado_equipo VALUES ("","Bueno");
INSERT INTO estado_equipo VALUES ("","Con fallas");
INSERT INTO estado_equipo VALUES ("","Dañado");
INSERT INTO estado_equipo VALUES ("","Descompuesto");
INSERT INTO estado_equipo VALUES ("","En mantenimiento");
INSERT INTO estado_equipo VALUES ("","Inservible");
INSERT INTO estado_equipo VALUES ("","Nuevo");
INSERT INTO estado_equipo VALUES ("","Obsoleto");


/*Tabla paises*/
INSERT INTO pais VALUES ("","Antigua y Barbuda");
INSERT INTO pais VALUES ("","Argentina");
INSERT INTO pais VALUES ("","Bahamas");
INSERT INTO pais VALUES ("","Barbados");
INSERT INTO pais VALUES ("","Belice");
INSERT INTO pais VALUES ("","Bolivia");
INSERT INTO pais VALUES ("","Brasil");
INSERT INTO pais VALUES ("","Canada");
INSERT INTO pais VALUES ("","Chile");
INSERT INTO pais VALUES ("","Colombia");
INSERT INTO pais VALUES ("","Costa Rica");
INSERT INTO pais VALUES ("","Cuba");
INSERT INTO pais VALUES ("","Dominica");
INSERT INTO pais VALUES ("","Ecuador");
INSERT INTO pais VALUES ("","El Salvador");
INSERT INTO pais VALUES ("","Estados Unidos");
INSERT INTO pais VALUES ("","Granada");
INSERT INTO pais VALUES ("","Guatemala");
INSERT INTO pais VALUES ("","Guyana");
INSERT INTO pais VALUES ("","Haiti");
INSERT INTO pais VALUES ("","Honduras");
INSERT INTO pais VALUES ("","Jamaica");
INSERT INTO pais VALUES ("","Mexico");
INSERT INTO pais VALUES ("","Nicaragua");
INSERT INTO pais VALUES ("","Panama");
INSERT INTO pais VALUES ("","Paraguay");
INSERT INTO pais VALUES ("","Peru");
INSERT INTO pais VALUES ("","Republica Dominicana");
INSERT INTO pais VALUES ("","San Cristobal y Nieves");
INSERT INTO pais VALUES ("","San Vicente y las Granadinas");
INSERT INTO pais VALUES ("","Santa Lucia");
INSERT INTO pais VALUES ("","Surinam");
INSERT INTO pais VALUES ("","Trinidad y Tobago");

/*Estados*/
INSERT INTO estados VALUES ("2","Aguascalientes");
INSERT INTO estados VALUES ("3","Baja California");
INSERT INTO estados VALUES ("4","Baja California Sur");
INSERT INTO estados VALUES ("5","Campeche");
INSERT INTO estados VALUES ("6","Chihuahua");
INSERT INTO estados VALUES ("7","Chiapas");
INSERT INTO estados VALUES ("8","Coahuila de Zaragoza");
INSERT INTO estados VALUES ("9","Colima");
INSERT INTO estados VALUES ("10","Durango");
INSERT INTO estados VALUES ("11","Guanajuato");
INSERT INTO estados VALUES ("12","Guerrero");
INSERT INTO estados VALUES ("13","Hidalgo");
INSERT INTO estados VALUES ("14","Jalisco");
INSERT INTO estados VALUES ("15","Mexico");
INSERT INTO estados VALUES ("16","Michoacan de Ocampo");
INSERT INTO estados VALUES ("17","Morelos");
INSERT INTO estados VALUES ("18","Nayarit");
INSERT INTO estados VALUES ("19","Nuevo Leon");
INSERT INTO estados VALUES ("20","Oaxaca");
INSERT INTO estados VALUES ("21","Puebla");
INSERT INTO estados VALUES ("22","Queretaro");
INSERT INTO estados VALUES ("23","San Luis Potosi");
INSERT INTO estados VALUES ("24","Sinaloa");
INSERT INTO estados VALUES ("25","Sonora");
INSERT INTO estados VALUES ("26","Tamaulipas");
INSERT INTO estados VALUES ("27","Tlaxcala");
INSERT INTO estados VALUES ("28","Veracruz");
INSERT INTO estados VALUES ("29","Yucatan");
INSERT INTO estados VALUES ("30","Zacatecas");

/*Municipios*/
INSERT INTO municipio VALUES ("","Felipe Carrillo Puerto", 1);
INSERT INTO municipio VALUES ("","Isla Mujeres", 1);
INSERT INTO municipio VALUES ("","Othon P. Blanco", 1);
INSERT INTO municipio VALUES ("","Benito Juarez", 1);
INSERT INTO municipio VALUES ("","Jose Ma Morelos", 1);
INSERT INTO municipio VALUES ("","Lazaro Cardenas", 1);
INSERT INTO municipio VALUES ("","Solidaridad", 1);
INSERT INTO municipio VALUES ("","Tulum", 1);
INSERT INTO municipio VALUES ("","Bacalar", 1);
INSERT INTO municipio VALUES ("","Puerto Morelos", 1);
INSERT INTO municipio VALUES ("","Alvaro Obregon", 15);
INSERT INTO municipio VALUES ("","Azcapotzalco", 15);
INSERT INTO municipio VALUES ("","Coyoacan", 15);
INSERT INTO municipio VALUES ("","Cuajimalpa de Morelos", 15);
INSERT INTO municipio VALUES ("","Cuauhtemoc", 6);
INSERT INTO municipio VALUES ("","Gustavo A Madero", 15);
INSERT INTO municipio VALUES ("","Iztapalapa", 15);
INSERT INTO municipio VALUES ("","Magdalena Contreras", 15);
INSERT INTO municipio VALUES ("","Miguel Hidalgo", 15);
INSERT INTO municipio VALUES ("","Milpa Alta", 15);
INSERT INTO municipio VALUES ("","Tlahuac", 15);
INSERT INTO municipio VALUES ("","Tlalpan", 15);
INSERT INTO municipio VALUES ("","Venustiano Carranza", 15);
INSERT INTO municipios VALUES ("","Xochimilco", 15);

/*PUESTOS*/
INSERT INTO puesto VALUES (1,"Gerente comercial");
INSERT INTO puesto VALUES ("","Asistente de mercadotecnia");
INSERT INTO puesto VALUES ("","Gerente de capital humano");
INSERT INTO puesto VALUES ("","Asistente de capital humano");
INSERT INTO puesto VALUES ("","Auxiliar de capital humano");
INSERT INTO puesto VALUES ("","Contador");
INSERT INTO puesto VALUES ("","Contador general");
INSERT INTO puesto VALUES ("","Auxiliar contable");
INSERT INTO puesto VALUES ("","Encargado de tesoreria");
INSERT INTO puesto VALUES ("","Auxiliar de tesoreria");
INSERT INTO puesto VALUES ("","Encargado de facturacion");
INSERT INTO puesto VALUES ("","Auxiliar de facturacion");
INSERT INTO puesto VALUES ("","Encargado de cuentas por pagar");
INSERT INTO puesto VALUES ("","Encargado de cuentas por cobrar");
INSERT INTO puesto VALUES ("","Gerente de nominas");
INSERT INTO puesto VALUES ("","Auxiliar de nominas");
INSERT INTO puesto VALUES ("","Gerente de TI");
INSERT INTO puesto VALUES ("","Auxiliar de TI");
INSERT INTO puesto VALUES ("","Encargado de desarrollo");
INSERT INTO puesto VALUES ("","Programador JR");
INSERT INTO puesto VALUES ("","Programador SR");
INSERT INTO puesto VALUES ("","Encargado juridico");

/*Departamento*/
INSERT INTO departamento VALUES ("","Mercadotecnia","","");
INSERT INTO departamento VALUES (3,"Capital Humano","2023-06-26 08:56:00","");
INSERT INTO departamento VALUES ("","Gerencia General","26/06/2023 8:56 PM","");
INSERT INTO departamento VALUES ("","Direccion General","26/06/2023 8:56 PM","");
INSERT INTO departamento VALUES ("","Capital Humano","26/06/2023 8:56 PM","");
INSERT INTO departamento VALUES ("","Contabilidad","26/06/2023 8:56 PM","");
INSERT INTO departamento VALUES ("","Tesoreria","26/06/2023 8:56 PM","");
INSERT INTO departamento VALUES ("","Facturacion","26/06/2023 8:56 PM","");
INSERT INTO departamento VALUES ("","Mantenimiento","26/06/2023 8:56 PM","");
INSERT INTO departamento VALUES ("","Juridico","26/06/2023 8:56 PM","");
INSERT INTO departamento VALUES ("","Tecnologias de la Informacion","","");

/*Estatus_tickets*/
INSERT INTO estatus_ticket VALUES ("","Nuevo");
INSERT INTO estatus_ticket VALUES ("","Abierto");
INSERT INTO estatus_ticket VALUES ("","En espera");
INSERT INTO estatus_ticket VALUES ("","Cerrado");
INSERT INTO estatus_ticket VALUES ("","Pendiente");

/*COMPONENTES*/
    INSERT INTO componentes VALUES ("","ADAPTADOR THUNDERBOLT A GIGABIT ETHERNET","","");
    INSERT INTO componentes VALUES ("","ADAPTADOR USB A ETHERNET","","");
    INSERT INTO componentes VALUES ("","APUNTADOR","","");
    INSERT INTO componentes VALUES ("","BARRA DE MULTICONTACTO","","");
    INSERT INTO componentes VALUES ("","BASE DE TELEFONO IP","","");
    INSERT INTO componentes VALUES ("","BATERIA DE LAPTOP","","");
    INSERT INTO componentes VALUES ("","BATERIA UPS","","");
    INSERT INTO componentes VALUES ("","BOCINAS","","");
    INSERT INTO componentes VALUES ("","CABLE HDMI","","");
    INSERT INTO componentes VALUES ("","CABLE USB","","");
    INSERT INTO componentes VALUES ("","CABLE VGA","","");
    INSERT INTO componentes VALUES ("","CARGADOR","","");
    INSERT INTO componentes VALUES ("","CARTUCHO DE TINTA","","");
    INSERT INTO componentes VALUES ("","CHAROLA PARA RACKS","","");
    INSERT INTO componentes VALUES ("","CINTA","","");
    INSERT INTO componentes VALUES ("","CONVERTIDOR","","");
    INSERT INTO componentes VALUES ("","DISCO DURO HDD","","");
    INSERT INTO componentes VALUES ("","DISCO DURO SSD","","");
    INSERT INTO componentes VALUES ("","DISPLAY","","");
    INSERT INTO componentes VALUES ("","FUENTE DE PODER","","");
    INSERT INTO componentes VALUES ("","GABINETE","","");
    INSERT INTO componentes VALUES ("","KIT TECLADO MOUSE USB","","");
    INSERT INTO componentes VALUES ("","LAPIZ STYLUS","","");
    INSERT INTO componentes VALUES ("","MEMORIA RAM","","");
    INSERT INTO componentes VALUES ("","MEMORIA USB","","");
    INSERT INTO componentes VALUES ("","MICROFONO","","");
    INSERT INTO componentes VALUES ("","MOUSE","","");
    INSERT INTO componentes VALUES ("","MULTICONTACTO PARA RACKS","","");
    INSERT INTO componentes VALUES ("","MULTIPUERTOS USB","","");
    INSERT INTO componentes VALUES ("","PROCESADOR","","");
	INSERT INTO componentes VALUES ("","SIN MARCA","","");
    INSERT INTO componentes VALUES ("","SOPORTE PARA PROYECTOR","","");
    INSERT INTO componentes VALUES ("","TARJETA DE RED WIFI USB","","");
    INSERT INTO componentes VALUES ("","TARJETA MADRE","","");
    INSERT INTO componentes VALUES ("","TARJETA RED PCI EXPRESS","","");
    INSERT INTO componentes VALUES ("","TECLADO","","");
    INSERT INTO componentes VALUES ("","TECLADO ALFANUMERICO","","");
    INSERT INTO componentes VALUES ("","TECLADO EXTERNO NUMERICO","","");
    INSERT INTO componentes VALUES ("","TECLADO PS2","","");
    INSERT INTO componentes VALUES ("","TRANSCEND","","");
    INSERT INTO componentes VALUES ("","UNIDAD DVD/WRITER","","");

/*PAQUETERIAS*/

INSERT INTO paqueteria VALUES("","ADMI","ADMINPAQ");
INSERT INTO paqueteria VALUES("","ADOC","ADOBE CREATIVE CLOUD");
INSERT INTO paqueteria VALUES("","ESET","ANTIVIRUS ESET");
INSERT INTO paqueteria VALUES("","KAS","ANTIVIRUS KASPERSKY");
INSERT INTO paqueteria VALUES("","CCON","CONTPAQ CONTABILIDAD");
INSERT INTO paqueteria VALUES("","CNOM","CONTPAQ NOMINAS");
INSERT INTO paqueteria VALUES("","CCOM","CONTPAQ COMERCIAL");
INSERT INTO paqueteria VALUES("","LOFI","LIBRE OFFICE");
INSERT INTO paqueteria VALUES("","MINM","MINDJET MINMANAGER");
INSERT INTO paqueteria VALUES("","M365","OFFICE 365");
INSERT INTO paqueteria VALUES("","O13H","MS OFFICE 2013 H&B");
INSERT INTO paqueteria VALUES("","O16H","MS OFFICE 2016 H&B");
INSERT INTO paqueteria VALUES("","O19H","MS OFFICE 2019 H&B");
INSERT INTO paqueteria VALUES("","O21H","MS OFFICE 2021 H&B");
INSERT INTO paqueteria VALUES("","O13P","MS OFFICE PROFESIONAL 2013");
INSERT INTO paqueteria VALUES("","O16P","MS OFFICE PROFESIONAL 2016");
INSERT INTO paqueteria VALUES("","O19P","MS OFFICE PROFESIONAL 2019");
INSERT INTO paqueteria VALUES("","O21P","MS OFFICE PROFESIONAL 2021");
INSERT INTO paqueteria VALUES("","NPRO","NITRO PDF PRO");
INSERT INTO paqueteria VALUES("","SQ19","SQL SERVER 2019 STD");
INSERT INTO paqueteria VALUES("","TV11","TEAMVIEWER 11");
INSERT INTO paqueteria VALUES("","TV12","TEAMVIEWER 12");
INSERT INTO paqueteria VALUES("","TV13","TEAMVIEWER 13");
INSERT INTO paqueteria VALUES("","TV14","TEAMVIEWER 14");

/*SISTEMA OPERATIVO*/
INSERT INTO so VALUES(1,"Android");
INSERT INTO so VALUES(2,"Freenas");
INSERT INTO so VALUES(3,"IOS");
INSERT INTO so VALUES(4,"Linux");
INSERT INTO so VALUES("","Mac OS");
INSERT INTO so VALUES("","MS Win 10 Profesional");
INSERT INTO so VALUES("","MS Win 10 Standard");
INSERT INTO so VALUES("","MS Win 10 Home");
INSERT INTO so VALUES("","MS Win 10 Single Language");
INSERT INTO so VALUES("","MS Win 11 Profesional");
INSERT INTO so VALUES("","MS Win 11 Standard");
INSERT INTO so VALUES("","MS Win 11 Home");
INSERT INTO so VALUES("","MS Win 11 Single Language");
INSERT INTO so VALUES("","MS Win Server 2008 R2 Standard");
INSERT INTO so VALUES("","MS Win Server 2008 R2 Enterprise");
INSERT INTO so VALUES("","MS Win Server 2012 R2 Standard");
INSERT INTO so VALUES("","MS Win Server 2012 R2 Essentials");
INSERT INTO so VALUES("","MS Win Server 2012 R2 Datacenter");
INSERT INTO so VALUES("","MS Win Server 2016 Standard");
INSERT INTO so VALUES("","MS Win Server 2016 Essentials");
INSERT INTO so VALUES("","MS Win Server 2016 Datacenter");
INSERT INTO so VALUES("","MS Win Server 2019 Standard");
INSERT INTO so VALUES("","MS Win Server 2019 Essentials");
INSERT INTO so VALUES("","MS Win Server 2019 Datacenter");
INSERT INTO so VALUES("","MS Win Server 2022 Standard");
INSERT INTO so VALUES("","MS Win Server 2022 Essentials");
INSERT INTO so VALUES("","MS Win Server 2022 Datacenter");

/*MARCA*/
INSERT INTO marca VALUES(1,"3COM");
INSERT INTO marca VALUES(2,"A8X");
INSERT INTO marca VALUES(3,"ACER");
INSERT INTO marca VALUES("","ACP");
INSERT INTO marca VALUES("","ACTEK");
INSERT INTO marca VALUES("","ACTIVE COOL");
INSERT INTO marca VALUES("","ADATA");
INSERT INTO marca VALUES("","ALLEN&HEATH");
INSERT INTO marca VALUES("","AMD");
INSERT INTO marca VALUES("","AMIGO");
INSERT INTO marca VALUES("","AOC");
INSERT INTO marca VALUES("","AOPEN");
INSERT INTO marca VALUES("","APC");
INSERT INTO marca VALUES("","APPLE");
INSERT INTO marca VALUES("","ASROCK");
INSERT INTO marca VALUES("","ASUS");
INSERT INTO marca VALUES("","AVITECH");
INSERT INTO marca VALUES("","AXIS");
INSERT INTO marca VALUES("","BENQ");
INSERT INTO marca VALUES("","BOE");
INSERT INTO marca VALUES("","BROTHER");
INSERT INTO marca VALUES("","CANON");
INSERT INTO marca VALUES("","CASE LOGIC");
INSERT INTO marca VALUES("","CBL");
INSERT INTO marca VALUES("","CDP");
INSERT INTO marca VALUES("","CISCO");
INSERT INTO marca VALUES("","CNB");
INSERT INTO marca VALUES("","COMPAQ");
INSERT INTO marca VALUES("","COMPLETE");
INSERT INTO marca VALUES("","CORSAIR");
INSERT INTO marca VALUES("","CROSSMATCH");
INSERT INTO marca VALUES("","CYBERPOWER");
INSERT INTO marca VALUES("","DAHUA");
INSERT INTO marca VALUES("","DA-LITE");
INSERT INTO marca VALUES("","DATASHIELD");
INSERT INTO marca VALUES("","DELL");
INSERT INTO marca VALUES("","DELTA");
INSERT INTO marca VALUES("","DIGITALPERSONA");
INSERT INTO marca VALUES("","DIGITUS");
INSERT INTO marca VALUES("","D-LINK");
INSERT INTO marca VALUES("","DRAY TEK");
INSERT INTO marca VALUES("","DVE");
INSERT INTO marca VALUES("","DYMO");
INSERT INTO marca VALUES("","EAGLEEYES");
INSERT INTO marca VALUES("","EASY LINE");
INSERT INTO marca VALUES("","ECS");
INSERT INTO marca VALUES("","EDGE SYSTEMS");
INSERT INTO marca VALUES("","EDIMAX");
INSERT INTO marca VALUES("","ENGENIUS");
INSERT INTO marca VALUES("","ENSAMBLADA");
INSERT INTO marca VALUES("","EPCOM");
INSERT INTO marca VALUES("","EPSON");
INSERT INTO marca VALUES("","EVER POWER");
INSERT INTO marca VALUES("","EVOTEC");
INSERT INTO marca VALUES("","FORZA");
INSERT INTO marca VALUES("","FOXCONN");
INSERT INTO marca VALUES("","GATEWAY");
INSERT INTO marca VALUES("","GENERICO");
INSERT INTO marca VALUES("","GENIUS");
INSERT INTO marca VALUES("","GIGABYTE");
INSERT INTO marca VALUES("","GRANDSTREAM");
INSERT INTO marca VALUES("","HGST");
INSERT INTO marca VALUES("","HITACHI");
INSERT INTO marca VALUES("","HONOR ELECTRONIC");
INSERT INTO marca VALUES("","HP");
INSERT INTO marca VALUES("","HPE");
INSERT INTO marca VALUES("","HUAWEI");
INSERT INTO marca VALUES("","HYUNDAI ELECTRONICS");
INSERT INTO marca VALUES("","IBM");
INSERT INTO marca VALUES("","IMAC");
INSERT INTO marca VALUES("","INTEL");
INSERT INTO marca VALUES("","INTELLINET");
INSERT INTO marca VALUES("","ISB");
INSERT INTO marca VALUES("","KEMEX");
INSERT INTO marca VALUES("","KINGSTON");
INSERT INTO marca VALUES("","KLIP XTREME");
INSERT INTO marca VALUES("","KOBLENZ");
INSERT INTO marca VALUES("","LANIX");
INSERT INTO marca VALUES("","LEADER ELECTRONIC");
INSERT INTO marca VALUES("","LEGRAND");
INSERT INTO marca VALUES("","LENOVO");
INSERT INTO marca VALUES("","LG");
INSERT INTO marca VALUES("","LOGITECH");
INSERT INTO marca VALUES("","LYNKSYS");
INSERT INTO marca VALUES("","MANHATTAN");
INSERT INTO marca VALUES("","MARKVISION");
INSERT INTO marca VALUES("","MAXTOR");
INSERT INTO marca VALUES("","MICRON TECHNOLOGY");
INSERT INTO marca VALUES("","MICROSOFT");
INSERT INTO marca VALUES("","MOSHI");
INSERT INTO marca VALUES("","NACEB TECH");
INSERT INTO marca VALUES("","NEC");
INSERT INTO marca VALUES("","NEXXT");
INSERT INTO marca VALUES("","OVALTECH");
INSERT INTO marca VALUES("","PANASONIC");
INSERT INTO marca VALUES("","PERFECT CHOICE");
INSERT INTO marca VALUES("","PHILLIPS");
INSERT INTO marca VALUES("","POWERCOM");
INSERT INTO marca VALUES("","PROVISION");
INSERT INTO marca VALUES("","QNAP");
INSERT INTO marca VALUES("","QUALCOMM");
INSERT INTO marca VALUES("","RAMAXEL TECHNOLOGY");
INSERT INTO marca VALUES("","REALTEK");
INSERT INTO marca VALUES("","REVOLUTION");
INSERT INTO marca VALUES("","SAFETY");
INSERT INTO marca VALUES("","SAMSUNG");
INSERT INTO marca VALUES("","SANDISK");
INSERT INTO marca VALUES("","SAXXON");
INSERT INTO marca VALUES("","SBE TECH");
INSERT INTO marca VALUES("","SEAGATE");
INSERT INTO marca VALUES("","SECUCORE");
INSERT INTO marca VALUES("","SHURE");
INSERT INTO marca VALUES("","SICMA");
INSERT INTO marca VALUES("","SIN DATO");
INSERT INTO marca VALUES("","SMARTBITT");
INSERT INTO marca VALUES("","SONY VAIO");
INSERT INTO marca VALUES("","STARTECH");
INSERT INTO marca VALUES("","STEREN");
INSERT INTO marca VALUES("","SWICHI");
INSERT INTO marca VALUES("","TECHZONE");
INSERT INTO marca VALUES("","TECLADO EXTERNO NUMERICO");
INSERT INTO marca VALUES("","TENDA");
INSERT INTO marca VALUES("","TOSHIBA");
INSERT INTO marca VALUES("","TP-LINK");
INSERT INTO marca VALUES("","TPV");
INSERT INTO marca VALUES("","TRANSCEND");
INSERT INTO marca VALUES("","TRENDNET");
INSERT INTO marca VALUES("","TRIPPLITE");
INSERT INTO marca VALUES("","TRUE BASIX");
INSERT INTO marca VALUES("","UBIQUITI");
INSERT INTO marca VALUES("","VERBATIM");
INSERT INTO marca VALUES("","VERICO");
INSERT INTO marca VALUES("","VIEW SONIC");
INSERT INTO marca VALUES("","VISION");
INSERT INTO marca VALUES("","VOCE");
INSERT INTO marca VALUES("","VORAGO");
INSERT INTO marca VALUES("","VUTET");
INSERT INTO marca VALUES("","WESTERN DIGITAL");

/*EQUIPOS*/
INSERT INTO catalogo_equipo VALUES("ACP","ACCES POINT");
INSERT INTO catalogo_equipo VALUES("BAL","BALANCEADOR");
INSERT INTO catalogo_equipo VALUES("BAS","BASE PARA CPU");
INSERT INTO catalogo_equipo VALUES("BOC","BOCINAS");
INSERT INTO catalogo_equipo VALUES("CAM","CAMARA");
INSERT INTO catalogo_equipo VALUES("CEL","CELULAR");
INSERT INTO catalogo_equipo VALUES("LAP","COMPUTADORA PORTATIL");
INSERT INTO catalogo_equipo VALUES("PCE","COMPUTADORA DE ESCRITORIO");
INSERT INTO catalogo_equipo VALUES("PBX","CONMUTADOR");
INSERT INTO catalogo_equipo VALUES("DDE","DISCO DURO EXTERNO");
INSERT INTO catalogo_equipo VALUES("DIS","DISTRIBUIDOR UHF");
INSERT INTO catalogo_equipo VALUES("DVR","DVR");
INSERT INTO catalogo_equipo VALUES("ESC","ESCANER");
INSERT INTO catalogo_equipo VALUES("ETI","ETIQUETADORA");
INSERT INTO catalogo_equipo VALUES("FWL","FIREWALL");
INSERT INTO catalogo_equipo VALUES("IMP","IMPRESORA");
INSERT INTO catalogo_equipo VALUES("INY","IMPRESORA DE INYECCION DE TINTA");
INSERT INTO catalogo_equipo VALUES("MTZ","IMPRESORA DE MATRIZ DE PUNTO");
INSERT INTO catalogo_equipo VALUES("DES","IMPRESORA DESKJET");
INSERT INTO catalogo_equipo VALUES("LAS","IMPRESORA LASERJET");
INSERT INTO catalogo_equipo VALUES("MLT","IMPRESORA MULTIFUNCIONAL");
INSERT INTO catalogo_equipo VALUES("IPA","IPAD");
INSERT INTO catalogo_equipo VALUES("HUE","LECTOR DE HUELLA DIGITAL");
INSERT INTO catalogo_equipo VALUES("MEZ","MEZCLADORA");
INSERT INTO catalogo_equipo VALUES("MIC","MICROFONO");
INSERT INTO catalogo_equipo VALUES("MON","MONITOR");
INSERT INTO catalogo_equipo VALUES("PAN","PANTALLA DE PROYECCION");
INSERT INTO catalogo_equipo VALUES("PRO","PROYECTORPROYECTOR");
INSERT INTO catalogo_equipo VALUES("RAC","RACKS");
INSERT INTO catalogo_equipo VALUES("REC","RECEPTOR DE SEÑAL	");
INSERT INTO catalogo_equipo VALUES("REG","REGULADOR");
INSERT INTO catalogo_equipo VALUES("SVR","SERVIDOR");
INSERT INTO catalogo_equipo VALUES("SWC","SWITCH");
INSERT INTO catalogo_equipo VALUES("KVM","SWITCH KVM");
INSERT INTO catalogo_equipo VALUES("TAB","TABLET");
INSERT INTO catalogo_equipo VALUES("TEN","TECLADO EXTERNO NUMERICO");
INSERT INTO catalogo_equipo VALUES("TEL","TELEFONO");
INSERT INTO catalogo_equipo VALUES("TIP","TELEFONO IP");
INSERT INTO catalogo_equipo VALUES("NOB","UPS");